name: Weekly Backup

on:
  schedule:
    - cron: '0 4 * * 0' # Every Sunday at 04:00 UTC
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create backup archive
        run: |
          tar -czf monograph_backup_${{ github.run_number }}.tar.gz .
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monograph-weekly-backup
          path: monograph_backup_*.tar.gz
